spring:
  application:
    name: currency-service
  cache:
    caffeine:
      spec: expireAfterWrite=1h

api:
  central-bank:
    url: https://www.cbr.ru


resilience4j:
  circuitbreaker:
    instances:
      central-bank-service:
        base-config: default
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
server:
  servlet:
    encoding:
      force-request: true
      charset: UTF-8
  port: 8081
