server:
  servlet:
    context-path: /api
    encoding:
      force-response: true
      charset: UTF-8
api:
  kudago:
    base-path: https://kudago.com/public-api/v1.4
    max-threads: 5
    initialize-threads: 3
    init-data-rate: PT1H
  currency-service:
    base-path: localhost:8081