server:
  servlet:
    context-path: /api
    encoding:
      force-response: true
      charset: UTF-8
api:
  kudago:
    base-path: https://kudago.com/public-api/v1.4
    max-threads: 5
    initialize-threads: 3
    init-data-rate: PT1H
  currency-service:
    base-path: http://localhost:8081

spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/tinkoff-fintech
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate